# Site settings
title: SeanLi's Blog
url: "http://akldm007.github.io"
baseurl: ""
description: >
  If it doesn't Challenge you, it doesn't Change you

# Your information
email: sean.li02@sap.com
author: SeanLi
avatar: "/pic/jm.jpg"
profile: A knight
github_username: akldm007

# Build settings
permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

paginate: 6
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
